name: Build with vcpkg (Linux/Mac)

on:
  push:
    branches:
      - master
      - v*
    tags:
      - v*

  pull_request:
    branches:
      - master
      - v*

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.cxx }}-${{ matrix.buildtype }}-luajit=${{ matrix.luajit }}
    runs-on: ${{ matrix.os }}-${{ matrix.os-version }}
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        name: [ubuntu-gcc, macos-clang]
        buildtype: [Debug, Release]
        luajit: [on, off]
        include:
          - name: ubuntu-gcc
            os: ubuntu
            os-version: 22.04
            cxx: g++
            cc: gcc
            triplet: x64-linux
            packages: >
              boost-iostreams boost-asio boost-system boost-variant boost-lockfree glew
              boost-filesystem boost-uuid physfs openal-soft libogg libvorbis zlib opengl
          - name: macos-clang
            os: macos
            os-version: latest
            cxx: clang++
            cc: clang
            triplet: x64-osx
            packages: >
              boost-iostreams boost-asio boost-system boost-variant boost-lockfree glew
              boost-filesystem boost-uuid libogg libvorbis zlib opengl

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Ubuntu - install opengl lua5.1 luajit
        run: sudo apt-get install libglew-dev liblua5.1-0-dev libluajit-5.1-dev
        if: contains( matrix.os, 'ubuntu')

      - name: MacOS - install physfs pkgconfig lua5.1 luajit xquartz
        run: brew install physfs pkgconfig lua@5.1 luajit xquartz
        if: contains( matrix.os, 'macos')

      - name: Set Environment vars
        run: |
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV

      - name: Cache vcpkg
        uses: actions/cache@v3
        id: vcpkg-cache
        continue-on-error: true
        with:
          path: ${{ github.workspace }}/vcpkg
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgArguments: ${{ matrix.packages }}
          vcpkgDirectory: ${{ github.workspace }}/vcpkg/
          vcpkgTriplet: ${{ matrix.triplet }}
          vcpkgGitCommitId: 6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2

      - name: Cache build
        uses: actions/cache@v3
        id: build-cache
        continue-on-error: true
        with:
          path: ${{ github.workspace }}/build
          key: build-${{ runner.os }}-${{ matrix.buildtype }}-${{ matrix.luajit }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.buildtype }}-${{ matrix.luajit }}-

      - name: Build with CMake
        uses: lukka/run-cmake@v3
        with:
          buildDirectory: ${{ github.workspace }}/build
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE="${{ matrix.buildtype }}" -DLUAJIT="${{ matrix.luajit }}"'
          useVcpkgToolchainFile: true

      - name: dir
        run: find ${{ github.workspace }}
        shell: bash

      - name: Upload artifact binary
        uses: actions/upload-artifact@v4
        with:
          name: otclient-${{ matrix.name }}-${{ matrix.buildtype }}-luajit=${{ matrix.luajit }}-${{ github.sha }}
          path: ${{ github.workspace }}/build/otclient 